### ISSUE TITLE
Support molecule alignment based on a template 

### ISSUE THREAD

**Issue by MichelML** [iktos/molecule-representation#29]
It would be very nice to support this out of the box in `MoleculeRepresentation` https://www.rdkitjs.com/#drawing-molecules-constraints in your implementation.

Specs:
- offer a `template` prop on the MoleculeRepresentation component , which accepts a MolBlock string representing a substructure with 2D alignment coordinates information.  
- if `template` is defined and if `smiles` is passed to MoleculeRepresentation (not smarts), align smiles representation to template coordinates.

**Comment by RamziWeslati** [comment]
@MichelML Sure, we'll add that, thanks for the suggestion

**Comment by RamziWeslati** [comment]
Done in #40, feel free to run storybook to look up the props to pass.
